.TH "pickledTimesViewer.py" "1" "0.0.0" "Nicholas Lemay" "PxStats"
.SH "NAME"
.LP 
pickledTimesViewer.py \- Small debugging utility wich allows user to see the time of the last pickle updates of every client/sources found on the machine where this utility is run. 
.SH "SYNTAX"
.LP 
pickledTimesViewer.py 


.SH "DESCRIPTION"
.LP 
pickledTimesViewer.py \- Small debugging utility wich allows user to see the time of the last pickle updates of every client/sources found on the machine where this utility is run. 
.SH "DEFAULT VALUES"
No default values exists since no options exist in the current version of this program.
.SH "OPTIONS"
No options exists for this program at the moment. 

.SH "FILES"
.BR 
.TP 
The following standard python modules are required :
.TP 
\fIos,sys,pickle \fP 
.TP 
The following stats library modules are required :  
.TP 
\fIStatsPaths\fP
.SH "ENVIRONMENT VARIABLES"
.BR 
.TP 
\fBPXROOT\fP
Specifies the where metPx was installed.

.SH "EXAMPLES"
python weekyGraphicsWebPage.py

****IMPORTANT NOTES :
.TP 
This is the only way to use this program at the moment. 





.SH "AUTHORS"
.BR 
Nicholas Lemay <nicholas.lemay@ec.gc.ca>




.SH "SEE ALSO"
.TP 

\fB".../px/stats/doc/"\fR wich contains infos for both users and developers.
