#!/bin/ksh

# just run this script and as argument give a branch px version
# at sourceforge and you will get a file px*.deb which will be
# the package debian install file

# argument 1 is metpx version... 

  if [[ $# != 1 ]]; then
     echo "Usage : " $0 "svn-version"
     echo 
     echo "      example : " $0 "px-0-4-3"
     exit 1
  fi

# checking out version

  svn checkout https://metpx.svn.sourceforge.net/svnroot/metpx/branches/$1

  if [[ $? != 0 ]]; then
     echo 
     echo "Error: could not checkout " $1
     exit 2
  fi

# define SVN and DEB packages

  SVN_PACKAGE=$1

  DEB_NAME=px
  DEB_VERSION=`echo $1 | sed 's/px-//' | sed 's/-/./g'`
  DEB_PACKAGE=${DEB_NAME}${DEB_VERSION}

##############################################
# /usr/bin  ...  executables
##############################################

  SVN_BIN=$SVN_PACKAGE/sundew/bin
  DEB_BIN=/usr/bin

  mkdir -p  $DEB_PACKAGE/$DEB_BIN
  rm -r -f  $SVN_BIN/.svn
  cp -r     $SVN_BIN/* $DEB_PACKAGE/$DEB_BIN

# tools migration (goes into bin)

  SVN_TOOLS=$SVN_PACKAGE/sundew/tools

  cp $SVN_TOOLS/mr-clean $DEB_PACKAGE/$DEB_BIN

##############################################
# /usr/lib  ... package lib requierements
##############################################

  SVN_LIB=$SVN_PACKAGE/sundew/lib
  DEB_LIB=/usr/lib/$DEB_NAME

  mkdir -p  $DEB_PACKAGE/$DEB_LIB
  rm -r -f  $SVN_LIB/.svn $SVN_LIB/*/.svn $SVN_LIB/*/*/.svn
  rm -r -f  $SVN_LIB/importedLibs/paramiko
  rm -r -f  $SVN_LIB/importedLibs/Crypto
  rm -r -f  $SVN_LIB/importedLibs/.*tar*
  cp -r     $SVN_LIB/* $DEB_PACKAGE/$DEB_LIB

##############################################
# /usr/share/man  ... package manpages
##############################################

  SVN_MAN=$SVN_PACKAGE/sundew/man
  DEB_MAN=/usr/share/man

  mkdir -p  $DEB_PACKAGE/$DEB_MAN
  rm -r -f  $SVN_MAN/.svn $SVN_MAN/*/.svn $SVN_MAN/*/*/.svn
  cp -r     $SVN_MAN/* $DEB_PACKAGE/$DEB_MAN

##############################################
# /usr/share/doc  ... package documentation
##############################################

  SVN_DEB=$SVN_PACKAGE/sundew/debian
  DEB_DOC=/usr/share/doc/$DEB_PACKAGE

  mkdir -p $DEB_PACKAGE/$DEB_DOC
  rm -r -f $SVN_DEB/.svn
  cp -r    $SVN_PACKAGE/sundew/etc $DEB_PACKAGE/$DEB_DOC
  cp       $SVN_DEB/c* $DEB_PACKAGE/$DEB_DOC
  rm       $DEB_PACKAGE/$DEB_DOC/control

##############################################
# /var/spool/px  ... database/queue parent dir
##############################################

  mkdir -p $DEB_PACKAGE/var/spool/px

##############################################
# /etc/px        ... configurations parent dir
##############################################

  mkdir -p $DEB_PACKAGE/etc/px

cat > $DEB_PACKAGE/etc/px/px.conf << EOF4
# this file contains the basic configuration for METPX to run properly
# Will be ignored if environment variable PXCONF defines another file

# the parent directory for all your processes'configurations
# Will be ignored if environment variable PXROOT defines another directory
#pxroot /etc/px

# the directory where the database will reside
# Will be ignored if environment variable PXDATA defines another directory
#pxdata /var/spool/px

# the directory where the package libraries reside
# Will be ignored if environment variable PXLIB defines another directory
#pxlib /usr/lib/px

# the directory where the logs will be written
# Will be ignored if environment variable PXLOG defines another directory
#pxlog /var/log/px

# the default extension for all products 
# should be redefined for any receiver that is not using bulletin
#extension -NAME:-CCCC:-TT:-CIRCUIT:Direct

EOF4

##############################################
# /var/log/px    ... log parent dir
##############################################

  mkdir -p $DEB_PACKAGE/var/log/px
  
##############################################
# DEBIAN     package description/control files
##############################################

  DEB_DEBIAN=$DEB_PACKAGE/DEBIAN
  mkdir -p   $DEB_DEBIAN

# create file control

cat > $DEB_DEBIAN/control << EOF5
Package: $DEB_NAME
Version: $DEB_VERSION
Section: misc
Priority: optional
Architecture: i386
Depends: python (>= 2.4), python-paramiko
Maintainer: Peter Silva <peter.silva@ec.gc.ca>
Description: MetPX is a WMO TCP/IP GTS message switching system
 WMO - World Meteorological Organization,
 GTS - Global Telecommunications System circuits based on TCP/IP.
 Developed at the Canadian Meteorological Centre of Environment
 Canada for our local use.
 web site: http://metpx.sourceforge.net/
EOF5

# create debian package

dpkg-deb --build $DEB_PACKAGE

echo ' to install : dpkg -i ' ${DEB_PACKAGE}.deb
echo ' to remove  : dpkg -r ' $DEB_NAME
