.TH hang_check "1" "Jan 2007" "px 1.0.0" "Metpx suite"
.SH NAME
hang_check \- Metpx script to check that no process is hang
.SH SYNOPSIS
.B hang_check
.SH DESCRIPTION
.PP
Automatically set in the crontab.
This solve the problem when an client has a communication problem.
If the timeout is not set it may happen that the process hangs forever.
The script check the age of the log file, and the age of the file in queue.
If a file has been sitting there for more than 5 mins and nothing is logged
than the process is restarted.
.PP
