.TH pxFlowNames "1" "Jan 2007" "px 1.0.0" "Metpx suite"
.SH NAME
pxFlowNames \- Metpx adhoc script to list all implemented metpx process
.SH SYNOPSIS
.B pxFlowNames
.SH DESCRIPTION
.PP
This script just lists all the receivers, filters, senders name.
It can be used to give you the list of process to check, or log files
or whatever.
