.TH pxRetrans "1" "Jan 2007" "px 1.0.0" "Metpx suite"
.SH NAME
pxRetrans \- Metpx adhoc tool to retransmit products to clients.
.SH SYNOPSIS
.B pxRetrans 
.SH DESCRIPTION
.PP
pxRetrans is an command line interpretor. It supports many commands.
It is out of the scope of this manpage to go through all the commands
and the possibilities of this program. Simply lauch pxRetrans and use
"h" or "?" to help you through its capabilities.
