.TH pxValidator "1" "Jan 2007" "px 1.0.0" "Metpx suite"
.SH NAME
pxValidator \- Metpx adhoc tool to check the syntax and the modifications made
to a routing table files and/or the stations.conf file
.SH SYNOPSIS
.B pxValidator 
 [\fI-r routingFile\fR] [\fI-s stations.conf\fR] 
.SH DESCRIPTION
.PP
Automatically set in the crontab. It is called with its default
parameters which is to remove 30 days old products. There are
two ways to set up another removal limit. The first is to change
the crontab line and add the parameter "--days x" in command line or
to change the parameter "daysToKeepInDB x" in the global metpx
configuration file /etc/px/px.conf
.PP
.nf

.B pxDBCleaner
.B pxDBCleaner --days x

.fi
.PP
The action argument does simply what it means.
