#!/bin/sh
#
# initpx  -- initialize the PX directory tree.
#
set -x

if [ ! "${PXROOT}" ]; then
  export PXROOT=/apps/px
fi

if [ ! -d ${PXROOT} ]; then
   mkdir ${PXROOT}
fi

if [ ! "`grep px /etc/group`" ]; then 
    addgroup --system px
fi
if [ ! "`grep px /etc/passwd`" ]; then 
    adduser --system --home ${PXROOT} --shell /bin/bash  --ingroup=px px
fi

chown -R px.px ${PXROOT}
 
if [ -d bin -a -d lib -a -d tools -a -d ${PXROOT} ]; then

  cp -r -p mode bin lib tools ${PXROOT}
  if [ ! -d ${PXROOT}/etc ]; then
     mkdir ${PXROOT}/etc ${PXROOT}/etc/tx ${PXROOT}/etc/rx 
  fi
  if [ ! -d ${PXROOT}/db ]; then
     mkdir ${PXROOT}/db ${PXROOT}/txq ${PXROOT}/rxq ${PXROOT}/log
     chgrp px ${PXROOT}/db ${PXROOT}/txq ${PXROOT}/rxq ${PXROOT}/log
     chown px ${PXROOT}/db ${PXROOT}/txq ${PXROOT}/rxq ${PXROOT}/log
  fi

  echo "init ran"
else
  echo "init failed, must be invoked in sundew root directory"
fi

